name: Build on release

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          filename: pridemoji.zip
          directory: dist

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/pridemoji.zip
          fail_on_unmatched_files: true
